### ISSUE TITLE
Activate/deactivate charger from Homey

### ISSUE THREAD

**Issue by vsurlien** [ricott/homey-no.easee#1]
Hi,

Is it possible to add an Action for "activate" and "deactivation" of the charger?
I have this charger installed in my cabin and want the charger to be deactivated (Not able to charge) when i am not in my cabin.

**Comment by ricott** [comment]
Sure thing, coming in version 0.9.3 that is waiting for Athom approval.
Please try it out and let me know what you think!

**Comment by vsurlien** [comment]
Perfect. I'll let you know.
