### ISSUE TITLE
Controlling individual phases

### ISSUE THREAD

**Issue by HenningCederquist** [ricott/homey-no.easee#10]
Hi. Does this flowcard actually work and does the Easee charger support to be controlled by individual phases?
It would be really useful these days!!
🤓👍

![42D99A2E-2AB1-4003-BA5F-DB4108558CD0](https://user-images.githubusercontent.com/88491386/144379358-d362e9ab-2e38-47b3-b581-b1f3edbb9de9.jpeg)

**Comment by ricott** [comment]
Hi!
What I have tested myself (some time ago) is to set 2 phases to 0 and one phase to the desired amps. By doing so you can force Easse to use a phase of your choice for single-phase charging. Mainly hybrid cars I assume

For three-phase charging, I suspect Eassee simple ignores the different values for each phase and use one of the amp settings across all phases.

Happy to learn the outcome if you perform some testing :)

**Comment by HenningCederquist** [comment]
Thanks for quick reply! Yes! You are right! If I set two of the values below 6A (6A is the minimum in Easee) it will pause and start 1-phase charging on the third phase according to that value.
But if all three values are within the set range 6-16A (in my case) Easee will use the lowest value for all three phases.
It seems like this is mainly a limitation of the cars (onboard charger) and not the Easee box itself. 
Anyway! Thanks again! Great app!!!!!
