### ISSUE TITLE
Card icon in the same style as other Homey icons

### ISSUE THREAD

**Issue by runemart** [ricott/homey-no.easee#11]
It would be really nice if the card had an icon that was in the same style as the other icons provided by Homey. 

I see there are a couple of designers from Homey that can even make icons for the integration: 
https://github.com/athombv/homey-vectors-public

![homey-easee](https://user-images.githubusercontent.com/117179/145982397-48bba52a-43de-4c43-8f07-7b781f781219.jpg)

**Comment by ricott** [comment]
Ticket created

**Comment by ricott** [comment]
Available in test version 1.2.7
