### ISSUE TITLE
Have Power summarizer to update more often. 

### ISSUE THREAD

**Issue by emilkola** [ricott/homey-no.easee#14]
Currently the power summarizer on the easse equalizer updates every hour,  it would be good if that could be updated more frequently 😊

**Comment by ricott** [comment]
I don't own an equaliser so hard to test myself. But the `meter_power` capability is updated via the SignalR stream provided by Easee cloud in the same way as all other values. If it isn't updated as frequently as the others that is because they don't send the value over the stream as often.

**Comment by emilkola** [comment]
Ah, ok. Thanks for the explanation.
That is probably right, not much to do about it 🤷‍♂️

tis 1 feb. 2022 kl. 20:05 skrev Richard Barkestam ***@***.***

**Comment by ricott** [comment]
Closing for now then 👍
