### ISSUE TITLE
Phases appear to be swapped

### ISSUE THREAD

**Issue by kmengvik** [ricott/homey-no.easee#16]
With 1-phase charging when I use phase 2-3, the app shows current on phase 1-2.

**Comment by ricott** [comment]
Not sure I can replicate that problem - doesn't mean it isn't there though.

This is charging my Volvo XC60 on one phase.
<img width="345" alt="image" src="https://user-images.githubusercontent.com/31240726/152865660-9fb385b4-ce96-438f-816c-586bb2af4dfc.png">

I have pinged my contact at Easee to verify the mapping I use, lets's see what he says.

**Comment by kmengvik** [comment]
![Bilde 08 02 2022, 09 00 16](https://user-images.githubusercontent.com/16176305/153035462-01daa938-cf88-4830-a68c-c836e191f1af.jpg)
![Bilde 08 02 2022, 08 59 24](https://user-images.githubusercontent.com/16176305/153035478-cd7ca092-b565-4381-993e-367d7cf001e4.jpg)

**Comment by ricott** [comment]
I see you have an IT grid type, that would explain it.
Hard for me to test since unfortunately the properties sent by Easee are different depending on grid type.
I published a test [version](https://homey.app/a/no.easee/test/) based on the comments I got from Easee. If this doesn't work I'd be interested to see the values that you get in the debug section of the device for the field "Last stream messages".

**Comment by kmengvik** [comment]
2022-02-09T12:52:17.576Z
'CircuitTotalPhaseConductorCurrent_L3' : '24.766000747680664'
,2022-02-09T12:52:17.577Z
'CircuitTotalPhaseConductorCurrent_L2' : '24.766000747680664'
,2022-02-09T12:53:31.719Z
'measure_power' : '5625'
,2022-02-09T12:55:58.873Z
'InVolt_T2_T4' : '231.5989990234375'
,2022-02-09T12:55:58.873Z
'measure_voltage' : '237'
,2022-02-09T12:55:58.884Z
'InVolt_T3_T4' : '225.64999389648438'
,2022-02-09T12:55:58.885Z
'TempMax' : '20'
,2022-02-09T12:56:25.907Z
'WiFiRSSI' : '-72'
,2022-02-09T12:57:15.600Z
'meter_power.lastCharge' : '1.8667124509811401'
,2022-02-09T12:57:24.585Z
'measure_power' : '5517'

**Comment by kmengvik** [comment]
![easee](https://user-images.githubusercontent.com/16176305/153215085-cf5712d3-f8d3-492a-befc-69fc5bc5548a.JPG)

**Comment by kmengvik** [comment]
In the debug, the current is on P2-P3, but frontend it is 1-2.

**Comment by ricott** [comment]
Correct, that is on purpose, mapping below for IT grid.
```
case 'inVoltageT2T3':
    this._updateProperty('measure_voltage', parseInt(data.value));
    break;
case 'inCurrentT3':
    this._updateProperty('measure_current.p1', data.value);
    break;
case 'inCurrentT4':
    this._updateProperty('measure_current.p2', data.value);
    break;
case 'inCurrentT5':
    this._updateProperty('measure_current.p3', data.value);
    break;
```

This is the data I got from Easee. inCurrentT1 doesn't seem to exist. inCurrentT2 is zero - thus 3-5 is mapped to phase 1-3 as per above. I hope this matches what is shown in the Easee app.
```
"inCurrentT2": 0.0,
"inCurrentT3": 0.009999999776482582,
"inCurrentT4": 0.008999999612569809,
"inCurrentT5": 0.009999999776482582,
```

This matches the mapping for TN grid where the mapping looks like this. Notice the field names are different, even if at first glance they look very similar.
```
case 'InVolt_T2_T3':
    this._updateProperty('measure_voltage', parseInt(data.value));
    break;
case 'InCurrent_T3':
    this._updateProperty('measure_current.p1', data.value);
    break;
case 'InCurrent_T4':
    this._updateProperty('measure_current.p2', data.value);
    break;
case 'InCurrent_T5':
    this._updateProperty('measure_current.p3', data.value);
    break;
```

**Comment by kmengvik** [comment]
Ok, what is the conclusion then? Is it possible to make an IT version of the app, or is what we got what we have to go with?

**Comment by ricott** [comment]
The conclusion is that mapping is as per above which includes IT and TN mapping in the same app in the version you currently have. 

Further, the conclusion is that you can't look for inCurrentT1 and think that should be P1 - thus me showing you the mapping. If you think mapping is inaccurate please show the Easse app vs the Homey app given the current version of the app.

**Comment by kmengvik** [comment]
That is already shown above. Ease app: L2-L3, Homey app: P1-P2. P3 is blank. Load should appear on P2-P3. Am I wrong?

**Comment by ricott** [comment]
Those screenshots were taken before I did all changes for IT net and released a test version
How does it look today - assuming you have installed the test version?

**Comment by kmengvik** [comment]
Yes, also the screenshot from the test version is posted above.

**Comment by ricott** [comment]
Here is the answer, will update and issue a new test version.

<img width="480" alt="image" src="https://user-images.githubusercontent.com/31240726/153411577-a56ba3b1-3100-41dd-b689-b53824f8d57b.png">

**Comment by ricott** [comment]
New version is live

**Comment by kmengvik** [comment]
Sorry, still the same. Uninstalled and reinstalled the test version. Was that the correct one?

Sendt fra min iPhone

**Comment by ricott** [comment]
Phase mapping for current is correct now in the code, no hesitation from my side around that.
For IT grid (as per the image above)
inCurrentT2 -> L1
inCurrentT3 -> L2
inCurrentT4 -> L3

The only other obvious source of error could potentially be grid type.
If you open advanced settings of the charger in Homey, what is the power grid type?
<img width="398" alt="image" src="https://user-images.githubusercontent.com/31240726/153606304-73393dc1-90e5-44f9-b66e-192316144554.png">

**Comment by kmengvik** [comment]
Downloaded app again. Now there is not current on any phases.



Sendt fra min iPhone

**Comment by ricott** [comment]
The current should be 0 unless you are charging at the moment.

**Comment by kmengvik** [comment]
As you can see above, the charge effect is 5600W

Sendt fra min iPhone

**Comment by kmengvik** [comment]
Did you read my last message?

Sendt fra min iPhone

**Comment by ricott** [comment]
I saw your message, but don't have much to add 🤷‍♂️
Did you see my question about grid-type? 
https://github.com/ricott/homey-no.easee/issues/16#issuecomment-1036251506

I'm building these apps on a best effort basis with zero compensation. If you want to make faster progress or even make progress possible I need you to help with the analysis and compare what you see in the Homey app vs Easee app vs what you see in the Last stream messages. Not once when you opened the ticket but also again after the multiple code changes have been made.

I have sent out a request on the forum for feedback from more IT grid users, but maybe there aren't especially many around.

**Comment by kmengvik** [comment]
In the latest version of the app, the current on all phases are zero. Did you see my picture showing grid type?

Sendt fra min iPhone

**Comment by kmengvik** [comment]
![IMG_7526](https://user-images.githubusercontent.com/16176305/153721616-4b9be2d5-7184-4be4-989d-d9b2c6ef6b3d.PNG)
![IMG_7527](https://user-images.githubusercontent.com/16176305/153721618-875b6b35-c749-4ab8-aaaf-b29c544ff337.PNG)

**Comment by kmengvik** [comment]
I have been updating new data every time you've requested.

**Comment by ricott** [comment]
Now in the last message, I see the Power grid type picture 👍
Can you also share what you have in the "Last stream messages" for the device?
Since the fields differ from Easee if it is IT or TN grid it is very hard for me to figure out what goes wrong here. Different names of fields and different meanings.

**Comment by ricott** [comment]
One suspicion now would be that mapping to the IT grid works in the code, but Easee provided me with the wrong parameter names. Will be key to understanding what you have in last stream messages. The parameter names for Current and Voltage. Should be something similar to inCurrentTn and inVoltageTnTn - values for corresponding phase

**Comment by kmengvik** [comment]
I am afraid previousely when I've replied from email, the screenshots were not published. But I hope you've got the correct picture now. Here is the latest stream message: 2022-02-13T10:05:15.448Z
'meter_power' : '132.19513999999995'
,2022-02-13T10:05:15.449Z
'EnergyPerHour' : '0'
,2022-02-13T10:16:52.498Z
'TempMax' : '10'
,2022-02-13T10:16:52.500Z
'InVolt_T3_T4' : '237.3179931640625'
,2022-02-13T10:16:52.502Z
'InVolt_T2_T4' : '238.38400268554688'
,2022-02-13T10:16:52.503Z
'InVolt_T2_T3' : '242.23500061035156'
,2022-02-13T10:31:53.537Z
'InVolt_T2_T4' : '235.98699951171875'
,2022-02-13T10:31:53.538Z
'InVolt_T3_T4' : '236.9149932861328'
,2022-02-13T10:31:53.540Z
'InVolt_T2_T3' : '238.44700622558594'
,2022-02-13T10:31:53.541Z
'TempMax' : '10'

**Comment by ricott** [comment]
Changed voltage to InVolt_T2_T4.
The current properties are not available in what you copied above, but now I used the TN grid parameter names with mapping T2-T4 vs TN grid which has T3-T5.
Test version 1.3.0 is out

**Comment by kmengvik** [comment]
the test version is on the same link as before? I'll try again tomorrow while charging.

**Comment by ricott** [comment]
Yes, those links are static

**Comment by kmengvik** [comment]
![image](https://user-images.githubusercontent.com/16176305/153829081-10a25852-e97c-485c-b3ed-04517bcc7ef8.png)
![image](https://user-images.githubusercontent.com/16176305/153829161-e353ce40-e749-490d-8943-60f274ceb312.png)

Is correct now
