### ISSUE TITLE
No data from device

### ISSUE THREAD

**Issue by jahnkenneth** [ricott/homey-no.easee#22]
I get no readings from my Easee charger in Homey. Have tried deleting and readding device.
"Last stream messages" is empty.

Log: e0aa596f-3f06-4f12-8f0c-2a94bce03876

**Comment by ricott** [comment]
In the log I see this error

```
Error: Login failed! Call '/api/accounts/login' failed, HTTP status code '400', and message '{
  errorCode: 100,
  errorCodeName: 'InvalidUserPassword',
  type: null,
  title: 'Username or password is invalid',
  status: 400,
  detail: '[Empty in production]',
  instance: null,
  extensions: {}
}'
```

**Comment by jahnkenneth** [comment]
Correct, I engeres the wrong password when trying to log in the first time. On the second attempt I got it right and was logged in, and able to add the device. 
The device does not report any values.

**Comment by jahnkenneth** [comment]
Any update @ricott ?

**Comment by jahnkenneth** [comment]
@ricott ???

**Comment by ricott** [comment]
Hi!
I have a new rewrite of the app running locally removing the SignalR API and using the plain REST API. Will not push it before I go on vacation though, so expect it towards the end of July.

**Comment by ricott** [comment]
I got access to an equalizer from Easee and decided to release the test version 1.4.0 - please give it a go.

**Comment by ricott** [comment]
Lots of changes since this ticket was created, closing. 
Open a new ticket when using the latest app version, if the problem is still there.
