### ISSUE TITLE
Will not log in!

### ISSUE THREAD

**Issue by Julusmoen** [ricott/homey-no.easee#26]
![0E1F3F57-829A-4026-B622-BB2D1A7240CA](https://user-images.githubusercontent.com/30026349/178149279-9777086d-305a-4e87-9f3e-b819847de1be.png)

**Comment by ricott** [comment]
The error message you see here is from the Easee API. Not an error from the Homey app. 
The error indicates you have multiple accounts with the same phone number. Have you tried logging in with email?

**Comment by Julusmoen** [comment]
Hi!

In the easee app i have logged in with my email, but in your app i have to
log in with my phone number and I get this error.

søn. 10. jul. 2022 kl. 22:11 skrev Richard Barkestam <
***@***.***>:

**Comment by ricott** [comment]
It works with email as well. In the test version I have updated the field label.

**Comment by Julusmoen** [comment]
Thank you! Now i got it in👍😊

man. 11. jul. 2022 kl. 09:10 skrev Richard Barkestam <
***@***.***>:
