### ISSUE TITLE
updating data to other apps

### ISSUE THREAD

**Issue by kmengvik** [ricott/homey-no.easee#27]
Hi again Richard,

Question: I use the app Power by the hour to record consumption and calculate charge cost. Yesterday I did a small 5 kWh charge over an hour. The PBTH app did not record anything live. Said that it had not updated for 3 days. So my calculation returned zero cost for the charge. However, PBTH fetched the data later and displayed it in its consumption/cost history. The author of the PBTH app says the easee app did not provide live data for the session (one hour duration). Is this a flaw, or what can we say ablut this situation?

Please do not look at this as a complaint, I love the app. I use it to totally master the power consumption in my home. I am only trying to resolve the lack of live data for my flows :)

**Comment by ricott** [comment]
Hi!
Not sure which version of the app you are running, but will push the current test version to live. Guess Athom will have to approve it so will take a few days to hit live. It should resolve any issues with delays in updates.

**Comment by kmengvik** [comment]
Hi, thanks for response. I have the 1.4.1 eksperimentell version. Have changed the input to the other app from kWh to W for now, as that input seem to be updated live, while the kWh value is static for a long time..

**Comment by ricott** [comment]
Don't use the PBTH app myself, which field from the Easee app are you using?

**Comment by kmengvik** [comment]
Hi, I use the lifetime kWh value. I use it to calculate charge session cost. At charge start, the value is stored in a variable. When charge is complete, this value is subracted from current value. The problem seem to be that the lifetime value is updated very seldomly. approx once pr. hour.  After charge, when cost is calculated, the kWh value has not been updated, causing the calclulation beeing incorrect. If I do the calculation again in an hour, it is done with the correct values. I assume this is an issue with easee itself, and not much you can do to improve the data update frequency.

**Comment by kmengvik** [comment]
Don't think I can use last session. The calculation need live data as the price change every hour. But I have requested easee to send data more frequently.
