### ISSUE TITLE
Not able to add Easee chargers

### ISSUE THREAD

**Issue by KristianWaalberg** [ricott/homey-no.easee#28]
Have used this app for quite a while, however yesterday I noticed Homey could not reach my two chargers.
There was some error with "json", unfortunately I did not take a screenshot before I went to uninstall and install the app again.

Now I am not able to add the chargers again.
![Easee](https://user-images.githubusercontent.com/110223623/181708723-c36c5ea0-906c-414b-a997-3069e54a7306.jpg)

**Comment by ricott** [comment]
Which version of the Homey firmware are you using?
Which version of the Easee app are you using?

**Comment by ricott** [comment]
Reopen if problem is still there
