### ISSUE TITLE
Update price pr kWh from Tibber?

### ISSUE THREAD

**Issue by henninglensberg** [ricott/homey-no.easee#29]
Hi
Will it be possible to update price pr kWh + an % or fixed value in Easee from eg. Tibber?

**Comment by ricott** [comment]
Hi!
There is a test version, 1.4.3 with the added action `Set charging price`. You can use Tibber's `Price changed` as the trigger for a flow and the new action as action. Pass the params from the Tibber action as input.
Try it out and let me know what you think. 

Not sure what you mean with:
> \+ an % or fixed value

**Comment by henninglensberg** [comment]
Hi

How can I download the test version?
What I mean with + an % or fixed value is:
I wan to set charging price to “Tibber price” +eg. 0,05 NOK”

Tibber price = 5,00 NOK + 0,05 NOK = Chargeprice = 5,05 NOK

**Comment by henninglensberg** [comment]
Hi
You are close;)
I don't understand why I have do set Cost pr kWh twice. both utside parantece and inside divide by VAT.

I only need to use CurrentPrice from Tibber and calculate it self before updating chargingprice.


Eg:; Set charging price to {{(Current price + 0,01)*1,25}}

The result will then be price from Tibber + 0,01 NOK + VAT (in this case = 25%)

**Comment by ricott** [comment]
The Tibber trigger `Price changed` returns these three values; `total, energy, tax`. The Easee API accepts these three values; `costPerKWh, costPerKwhExcludeVat, vat`. In my test flow, I simple mapped these three values straight off.

If you want to recalculate the energy price excl. taxes then I understand it is messy to calculate the taxes. Guess there a different types of taxes and not all are easy %.

We could drop two of the cost values and only use one, but the question is which is most useful. Most people I imagine are interested in the `costPerKWh` which includes taxes since that is what you will be paying. Then with Tibber you anyhow have the price guarantee of 50% lower price for charging. I guess we could a factor which by default is 100%, ie nothing happens with the value. But you can set it to 50% or whatever and the price sent to the Easee API will be decreased/increased.

Will think about it and have another go tomorrow.

**Comment by henninglensberg** [comment]
Hi
I see, 
But why not make all variables so we can Calculate, and the VAT% is a fix number, so, if we can calculate all figures it might also be easy to calculate all values..
But, I think calculation is easy if we got the ppossibility for it.
OR, make 2 "then" flows :)

**Comment by ricott** [comment]
New test version 1.4.4. 
- Only one cost field `costPerKWh`
The Easee app only shows the `costPerKWh` value. Can't find any docs on what the other fields are used for so dropped them.
- Changed the field type to text, to be able to use the calculations you are after

**Comment by henninglensberg** [comment]
Thanx :)

**Comment by ricott** [comment]
I added VAT back, there is a new test version.
If you don't have VAT you can set it to 0, then it won't be sent to Easee.

**Comment by henninglensberg** [comment]
Hi

Thanx 😉



Med vennlig hilsen / Kind regards

Henning Lensberg
Sjefskonsulent – Senior Løsningsarkitekt

Mobil: +47 98 28 94 40
E-post: ***@***.******@***.***>

Value Retail Consulting AS




Fra: Richard Barkestam ***@***.***>
Sendt: søndag 14. august 2022 21:09
Til: ricott/homey-no.easee ***@***.***>
Kopi: Henning Lensberg ***@***.***>; Author ***@***.***>
Emne: Re: [ricott/homey-no.easee] Update price pr kWh from Tibber? (Issue #29)


I added VAT back, there is a new test version.
If you don't have VAT you can set it to 0, then it won't be sent to Easee.

**Comment by henninglensberg** [comment]
One last question, when will the version be public, så we can stop use test version?



Med vennlig hilsen / Kind regards

Henning Lensberg
Sjefskonsulent – Senior Løsningsarkitekt

Mobil: +47 98 28 94 40
E-post: ***@***.******@***.***>

Value Retail Consulting AS




Fra: Henning Lensberg
Sendt: mandag 15. august 2022 07:53
Til: ricott/homey-no.easee ***@***.***>
Emne: SV: [ricott/homey-no.easee] Update price pr kWh from Tibber? (Issue #29)

Hi

Thanx 😉



Med vennlig hilsen / Kind regards

Henning Lensberg
Sjefskonsulent – Senior Løsningsarkitekt

Mobil: +47 98 28 94 40
E-post: ***@***.******@***.***>

Value Retail Consulting AS




Fra: Richard Barkestam ***@***.******@***.***>>
Sendt: søndag 14. august 2022 21:09
Til: ricott/homey-no.easee ***@***.******@***.***>>
Kopi: Henning Lensberg ***@***.******@***.***>>; Author ***@***.******@***.***>>
Emne: Re: [ricott/homey-no.easee] Update price pr kWh from Tibber? (Issue #29)


I added VAT back, there is a new test version.
If you don't have VAT you can set it to 0, then it won't be sent to Easee.

**Comment by ricott** [comment]
Published it yesterday, Athom needs to approve it and they seem to take their time currently ... could be a week I guess.
