### ISSUE TITLE
Last charging session

### ISSUE THREAD

**Issue by jahnkenneth** [ricott/homey-no.easee#3]
World it be possible to get the following data to Homey?
- kWh charged last session
- Average speed last session

**Comment by ricott** [comment]
Last charge session is easy to add, already part of the status API, will add it.
Average speed, have you seen that somewhere?

**Comment by jahnkenneth** [comment]
👍🏻😀

I meant average charging speed last seasion, kW. 
Sorry if that was not clear. 🙂

**Comment by ricott** [comment]
Now I was unclear I feel 😀
Avg charging speed in kWh. Have you seen that info somewhere? In the session api I see there are start and end time for a session but that is for events car connected/disconnected, so not useful.

**Comment by jahnkenneth** [comment]
😅 No, haven’t seen this info anywhere. 
But if we have start and end time, and kW charged, could this not be calculated? 

I see now that you wrote connected and disconnected, so this could prove difficult 🙁

**Comment by ricott** [comment]
The only option I see now is if I try to calculate this in the app somehow capturing the start charge, end charge events. Will do a release with these new fields first at least; last charge session kWh and current month kWh. 
For the latter, I'm considering changing what I implemented now though, to not get current month charge kWh but charge kWh last 30 days instead.

**Comment by ricott** [comment]
Closing this for now, even without average speed last session
