### ISSUE TITLE
How to use schedule card

### ISSUE THREAD

**Issue by kmengvik** [ricott/homey-no.easee#30]
Hi Richard :) Thank you again for one of the most useful apps on the Homey platform. 

I have a question on how to use a card. The schedule card. I want the charger to wait until 22 oclock when I plug in, but not momentarily start/stop charge when I plug. I suppose this set up (attached) will do just that. But how is the card thought to be used from your side? Should I trigger the schedule card with a daily trigger card? In that case how is the repeat function to be used? Sorry for beeing a noob, but appreciate clarification :)

![schedule card](https://user-images.githubusercontent.com/16176305/183613410-e4b0adec-b81f-4555-9259-967fbb36e630.jpg)

**Comment by ricott** [comment]
Hi!

Based on my understanding (I don't use Homey to control the Easee chargers currently) the schedule is a one-off setting if you include `Repeat = Yes`. With the action you have in the picture the car should only charge between 22-06 every day. You only invoke the action once, then the schedule is set. You can verify the outcome of the actions in the [easee.cloud](https://easee.cloud/) webapp.

If you build a flow using a trigger I recommend using the output from the trigger in the condition. Something like the below

<img width="362" alt="image" src="https://user-images.githubusercontent.com/31240726/184374560-c6866329-8603-4cfe-97d5-83ca7a179a82.png">

**Comment by kmengvik** [comment]
Thank you, 

I chose a different approach. Added a lot of flexibility to concider a number of scenarioes. also can be overridden with Siri :)
![ladbilen](https://user-images.githubusercontent.com/16176305/184380405-b5971cd8-ea26-4153-ae12-545a13b1a5e5.JPG)

**Comment by ricott** [comment]
Looks nice! Need to start using the advanced flows myself 👍
