### ISSUE TITLE
Need card to set charger state to completed

### ISSUE THREAD

**Issue by kmengvik** [ricott/homey-no.easee#32]
Hi, sorry for creating a new issue.. My charger is stopped through this flow 
![image](https://user-images.githubusercontent.com/16176305/185072850-943718b3-d3ca-42f7-be7e-537b6794b13d.png)
But I need to also set the state to completed. I did not find this option in the then cards. Is it possible to create?

**Comment by ricott** [comment]
It is not possible to set the completed state of the charger, that comes from the progress of (I guess) communicating with the car.

If you are a bit techy you can see the API endpoints Easee offers [here](https://developer.easee.cloud/reference/post_api-chargers-id-settings). PUT/POST/DELETE means you are changing something.

**Comment by kmengvik** [comment]
Ok, thanks. I’ll make a worksround in the flow then 😉
