### ISSUE TITLE
Livstid strömexport uppdateras inte

### ISSUE THREAD

**Issue by emilkola** [ricott/homey-no.easee#33]
Sen några dagar tillbaks så har livstid strömexport slutat att uppdateras rörande Easee equlizer. Livstid strömimport funkar och alla andra värden..

**Comment by ricott** [comment]
Är detta fortfarande ett problem? Easee hade problem under ett par dagar vid denna tidpunkt.
Jag har ingen Equalizer själv, men har fått access till en demoenhet som Easee använder för tester. Den är uppdaterad verkar det som.

<img width="376" alt="image" src="https://user-images.githubusercontent.com/31240726/187230344-a090e964-05a0-41ec-813e-194f83d16004.png">

Ser du andra värden om du loggar in på [easee.cloud ](https://easee.cloud/) och tittar på equalizer där?
<img width="346" alt="image" src="https://user-images.githubusercontent.com/31240726/187231350-790884bd-0d62-42bc-8e75-5cc79876d0c6.png">

**Comment by emilkola** [comment]
Ah, tack för svar! som du är inne på så har inte värdet uppdaterats även om
jag loggar in på cloud.. får vända mig till Easee..
men ska prova med en omstart av Equalizern..

Tack!

Den mån 29 aug. 2022 kl 16:58 skrev Richard Barkestam <
***@***.***>:
