### ISSUE TITLE
Error controlling charger with Homey.

### ISSUE THREAD

**Issue by joakimroer** [ricott/homey-no.easee#35]
After last update I can't controll my Easee charger with Homey.
If I change settings in the Easee app on my phone it update in Homey.
If I make an flow in Homey it will not update status to rhe charger.
I have tried remove and add charger and restart homey.

**Comment by ricott** [comment]
Hi!

Which action are you trying to execute?
If you look under advanced settings, do you see anything in the field last API error?

**Comment by joakimroer** [comment]
Hi
Thanks for answer.
My charger suddenly decrease down to 0A and said waiting for charging. Then I set 32A and it started charging and the flows worked.
Very strange. I have not worked sine last update for about 3 weeks.

But here is the api error:

2022-09-04T21:16:07.364Z
Error: get '/api/sites/371152/circuits/354266/dynamicCurrent' failed, HTTP status code '504', and message ''upstream request timeout''
    at invoke (/lib/Easee.js:507:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)


Mvh Joakim Roer
41475363



-------- Opprinnelig melding --------
Fra: Richard Barkestam ***@***.***>
Dato: 04.09.2022 18:54 (GMT+01:00)
Til: "ricott/homey-no.easee" ***@***.***>
Ko: joakimroer ***@***.***>, Author ***@***.***>
Emne: Re: [ricott/homey-no.easee] Error controlling charger with Homey. (Issue #35)


Hi!

Which action are you trying to execute?
If you look under advanced settings, do you see anything in the field last API error?

**Comment by ricott** [comment]
They have been having some problems, from what I understood due to overloaded cloud servers. 
`upstream request timeout` would mean that the Easee cloud couldn't reach your charger (I guess, not my error message but comes from the Easee cloud API).
Communication looks like this
Homey Easee app -> Easee cloud -> your Easee charger
