### ISSUE TITLE
Schedule vs Deleted start

### ISSUE THREAD

**Issue by mackewigren** [ricott/homey-no.easee#36]
I have a question about “Create schedule”-functionality. When I use the Create Schedule Card the time is set as “Delayed start” in Easee-app, not as a schedule. It doesn’t matter if I use Repeat Yes or No. As I see it this only means that the charging will start at a time but not stop. Am I doing wrong?

**Comment by ricott** [comment]
The basic charge plan is what is in the app, https://developer.easee.cloud/docs/scheduling#basic-charge-plan.
The description for the start and stop time is the same as for the (new) weekly schedule. I haven't used it so don't know if it will stop charging at the stop time for any of the schedule types. Guess we would need to test it out.

**Comment by mackewigren** [comment]
Hi

I checked and started to test about this Basic Charge Plan. Would it be possible to set the Starttime and Stoptime with variables instead? Now it is hard to create a good automation. For example by using Tibber (or princess from others) I know that I should charge between for example 02:00 and 07:00 But then flow would be extremely complex if I would need to do all this in several ”threads”. But by storing for example 02:00 and 07:00 in two different variables in Logic I could the call this card to create schedule.

Off course the other way could be to let homey control it completely but it takes more commands at that time.

Best regards
Marcus



￼

-------------------------------------------------------------
Marcus Wigren	0733-983138
Rosenvägen 5	        
23735 Bjärred	        ***@***.***

**Comment by ricott** [comment]
There are quite a few changes in the current test version of the app, will ship to live some time end of this week beginning next I think. You can install the test version already now, or wait until live. It has improved on/off actions amongst other things.

If you want to control charging and charge when energy prices are low I would not use the schedule action.
1. Set access to locked using the easee mobile app
2. Use new turn on/off actions to start and stop charging.

By setting access to locked you prevent the car from starting to charge when you plug it in. You have to issue a start command (turn on in test version) to start charging.

**Comment by mackewigren** [comment]
I can wait until it is shipped then. Will be interesting. Then I can let Homey start charging as soon as my house battery is empty for the evening and the car is plugged in. 

Do I have to set locked every day? Or is it in locked state ”forever”. 

Best regards

Marcus

**Comment by ricott** [comment]
You set locked once, and then it stays.
In order to charge when access=locked you need to "authorize" the charger and this can be done via the Easee mobile app or by turning on the charger in the Homey app.

**Comment by mackewigren** [comment]
Hi

(Keep this in English so others can read, even if I found out that we are almost neighbors…)

I installed the TEST version 1.5.5. Not sure what you mean by LOCKED. Is it the ÅTKOMST (ACCESS) on the start screen what you mean? And should I then select ENDAST NYCKEL (ONLY KEY).

And after this I will be able to start the charging from Homey. And the only commands to use is Start and stop? So maybe I build a flow saying

Car connected
I price less than X
House battery not charging (no power for the car otherwise and better to charge house battery with cheap electricity and use Tibber Price Guarantee for car

This would make it a lot simpler off course.

Best regards
Marcus

**Comment by ricott** [comment]
Hi!

1. Correct, "key only". Then use turn-on and off actions that will issue start and stop commands.

2. If you have installed the test version once, I think you automatically get the next test version when I issue one. You can install the live version over the test version I believe, to make sure you don't get test versions.
