### ISSUE TITLE
Control Easee charger from another app, missing capabilities?

### ISSUE THREAD

**Issue by dooniem** [ricott/homey-no.easee#37]
Hi. Homey seems to let HomeyScript run flowcards from other apps, but not let running apps run flowcards from other apps. APIplaygound vs HomeyAPIApp - I’m told.

Could you edit some of your capabilities, make it possible to at least start and pause the charger from other apps? It’s over my head what needs to be done, I’m just a user of the app needing capabilities from this one. Maybe you understand the question?

**Comment by ricott** [comment]
Added to test version 1.4.9 that is released 👍

**Comment by ricott** [comment]
v 1.5.5 is out with the support
