### ISSUE TITLE
Charger status cards lost their settings with new update

### ISSUE THREAD

**Issue by kmengvik** [ricott/homey-no.easee#38]
Hi Richard. An awkward issue arrived with the new update. The existing charger state cards lost their settings. I can not recall their settings. So this is not good. How could this happen? 
![image](https://user-images.githubusercontent.com/16176305/195835493-b95e5e1a-db93-49a2-910f-bcf2890355e5.png)

**Comment by ricott** [comment]
Hi! This was discussed in the forum thread [here](https://community.homey.app/t/app-pro-easee-charger/31647/135?u=richard_b).
Sorry for the inconvenience :(

**Comment by kmengvik** [comment]
Thanks! Great app anyway.
