### ISSUE TITLE
Change state cards fail

### ISSUE THREAD

**Issue by stiped** [ricott/homey-no.easee#39]
Hi, I'm currently on version 1.5.5 and the 'set state to' flow-cards are failing when invoking api: https://developer.easee.cloud/reference/get_api-commands-device-command-ticks

Failed to change status to 'PAUSE'. Reason: get '/api/commands/<device>/<command>/<ticks>' failed, HTTP status code '404'

**Comment by ricott** [comment]
Hi!
Maybe you are the one that sent a manual diag report? I tried to reply to it but as usual these days my email bounced. Some glitch in Athom's system I guess.

Can you paste the content from the app settings, not the device but app settings. There you find some stats around API calls and their response codes.

I see in the diag report lots of status checks and multiple start/stop commands in a short time span. Might be worth looking at your flows to make sure they execute what you want.

Example from the diag report
[log] 2022-12-02 22:00:12 [ManagerDrivers] [Driver:charger] [Device:2e59e9c5-] [Hjemme (EHnnnnn)] Resuming charge
[log] 2022-12-02 22:07:12 [ManagerDrivers] [Driver:charger] [Device:2e59e9c5-] [Hjemme (EHnnnnn)] Stopping charge
[log] 2022-12-02 22:09:55 [ManagerDrivers] [Driver:charger] [Device:2e59e9c5-] [Hjemme (EHnnnnn)] Starting charge
[log] 2022-12-02 22:10:20 [ManagerDrivers] [Driver:charger] [Device:2e59e9c5-] [Hjemme (EHnnnnn)] Pausing charge
[log] 2022-12-02 22:11:18 [ManagerDrivers] [Driver:charger] [Device:2e59e9c5-] [Hjemme (EHnnnnn)] Starting charge

Then it seems like you set the dynamic circuit current to 11 amps every second minute even if seems like it already is 11 amps?

The general recommendation these days is to set access to locked (key only) using the easee mobile app. Then start and stop charging using the turn on/off action. It also works using the dynamic charger current to start and stop charging. Setting it to 0 stops charging and increasing it will start charging. Most cars need 6-7 amps to start charging though.

**Comment by Erikersnill** [comment]
I have the same problem.  This happen with changing status.  It seems like the status changes, but then it fails. Vhanging amps work fine.  This started about a week ago and I suspect Easee has changed the API

![image](https://user-images.githubusercontent.com/119931396/205874969-c2f1c1ed-e80f-4107-9c2f-959e0e86f6ac.png)

**Comment by ricott** [comment]
Action called `Toggle state` is deprecated, not that it should have anything to do with the error we see here from the Easee API. There is a new action named `Toggle on or off` which uses the same logic as the on/off capability in the device itself, the one you can manually click to turn on/off the charger.
Both actions however use the `commands` API endpoint to check if the charger accepted the command or not.
Easee seems to have put me on an ignore list so no hope of a reply, but I can ask them via slack if they have changed anything.

**Comment by ricott** [comment]
Seem consistent, tried a few actions and always get a 404.
Asked Easee on Slack, but don't get your hopes up ...

**Comment by Erikersnill** [comment]
Ok, thank you.  I also get that error on the actions, like turn on etc.  However, they do work – the charger turns on with the action “turn on”, but returns a 404. That again results in the advanced flow to stop with an error. 

 

Erik

 

Fra: Richard Barkestam ***@***.***> 
Sendt: tirsdag 6. desember 2022 16.19
Til: ricott/homey-no.easee ***@***.***>
Kopi: Erikersnill ***@***.***>; Comment ***@***.***>
Emne: Re: [ricott/homey-no.easee] Change state cards fail (Issue #39)

 

Seem consistent, tried a few actions and always get a 404.
Asked Easee on Slack, but don't get your hopes up ...
