### ISSUE TITLE
Can’t add charger

### ISSUE THREAD

**Issue by Retteph** [ricott/homey-no.easee#40]
Can’t add charger due to: Cannot read properties of null (reading
'forEach')

![759C9454-2AC5-42B0-B601-20D63E97E9FF](https://user-images.githubusercontent.com/120514138/207427779-93898de2-6997-401f-8953-3893d85e0526.png)

adding equalizer works

**Comment by ricott** [comment]
Did you try more than one time? Thinking if there could be a temporary communication problem?
Otherwise, we would need to find out what your product listing looks like.
This is the endpoint used, https://developer.easee.cloud/reference/get_api-accounts-products
It should look something like this. There should be one or more circuits and below that one or more chargers.
Can you login to the API portal and trigger the endpoint and show the JSON returned?

```
[
  {
    "id": 0,
    "siteKey": "string",
    "circuits": [
          {
            "id": 0,
            "siteId": 0,
            "circuitPanelId": 0,
            "panelName": "string",
            "ratedCurrent": 0,
            "chargers": [
              {
                "id": "string",
                "name": "string",
```

**Comment by Retteph** [comment]
[  {    "id": 16472,    "siteKey": "C8Q2-6222",    "name": "Hemmet",    "levelOfAccess": 1,    "address": {      "street": "Byvägen 17B",      "buildingNumber": "",      "zip": "91342",      "area": "Obbola",      "country": {        "id": "SE",        "name": "Sweden",        "phonePrefix": 0      },      "latitude": null,      "longitude": null,      "altitude": null    },    "siteType": 1,    "ratedCurrent": 25,    "partnerId": 66,    "circuits": [      {        "id": 15513,        "siteId": 16472,        "circuitPanelId": 4,        "panelName": "4",        "ratedCurrent": 16,        "chargers": [          {            "id": "EH229849",            "name": "Byvägen",            "levelOfAccess": 2,            "userRole": 1,            "productCode": 1,            "backPlate": {              "id": "8164518AC52104",              "masterBackPlateId": "8164518AC52104",              "name": null            },            "isTemporary": false,            "color": 1,            "createdOn": "2020-02-26T11:35:16.135849",            "updatedOn": "2020-12-23T16:04:18.795421"          }        ],        "masterBackplate": null,        "useDynamicMaster": false,        "parentCircuitId": null      }    ],    "equalizers": [      {        "id": "QH091793",        "name": "Byvägen",        "siteId": 16472,        "circuitId": null      }    ],    "userRole": 1,    "allowedSiteActions": []  },  {    "id": 409978,    "siteKey": "XKY4-6522",    "name": "Reseladdaren",    "levelOfAccess": 1,    "address": null,    "siteType": 1,    "ratedCurrent": 16,    "partnerId": 20,    "circuits": [      {        "id": 390287,        "siteId": 409978,        "circuitPanelId": 1,        "panelName": "1",        "ratedCurrent": 16,        "chargers": [          {            "id": "EHFM8A4N",            "name": "Reseladdaren",            "levelOfAccess": null,            "userRole": 1,            "productCode": 1,            "backPlate": {              "id": "8067F38A8F7604",              "masterBackPlateId": "8067F38A8F7604",              "name": null            },            "isTemporary": false,            "color": 1,            "createdOn": "2021-04-19T10:21:06.188058",            "updatedOn": "2022-10-16T19:11:49.365698"          }        ],        "masterBackplate": null,        "useDynamicMaster": false,        "parentCircuitId": null      }    ],    "equalizers": [],    "userRole": 1,    "allowedSiteActions": [      "AllowToConfigureLevelOfAccess"    ]  },  {    "id": 73010,    "siteKey": "5PEU-K222",    "name": "Bräskafors",    "levelOfAccess": 3,    "address": null,    "siteType": 1,    "ratedCurrent": 20,    "partnerId": 66,    "circuits": [      {        "id": 70946,        "siteId": 73010,        "circuitPanelId": 1,        "panelName": "1",        "ratedCurrent": 16,        "chargers": [          {            "id": "EH836015",            "name": "Bräskafors",            "levelOfAccess": 3,            "userRole": 1,            "productCode": 1,            "backPlate": {              "id": "806B909A858204",              "masterBackPlateId": "806B909A858204",              "name": null            },            "isTemporary": false,            "color": 1,            "createdOn": "2021-01-20T14:13:48.055945",            "updatedOn": "2021-03-06T11:46:45.647822"          }        ],        "masterBackplate": null,        "useDynamicMaster": false,        "parentCircuitId": null      }    ],    "equalizers": [      {        "id": "QH6YDMPL",        "name": "Bräskafors",        "siteId": 73010,        "circuitId": null      }    ],    "userRole": 1,    "allowedSiteActions": []  },  {    "id": 508237,    "siteKey": "AHM4-W522",    "name": "Strandvägen 25",    "levelOfAccess": 1,    "address": {      "street": "Strandvägen",      "buildingNumber": "32",      "zip": "91342",      "area": "Obbola",      "country": {        "id": "SE",        "name": "Sweden",        "phonePrefix": 0      },      "latitude": null,      "longitude": null,      "altitude": null    },    "siteType": 1,    "ratedCurrent": 16,    "partnerId": 20,    "circuits": null,    "equalizers": [      {        "id": "QHAHYCBR",        "name": "Strandvägen 25",        "siteId": 508237,        "circuitId": null      }    ],    "userRole": 2,    "allowedSiteActions": null  }]Skickat från min iPhone14 dec. 2022 kl. 11:02 skrev Richard Barkestam ***@***.***>:﻿
Did you try more than one time? Thinking if there could be a temporary communication problem?
Otherwise, we would need to find out what your product listing looks like.
This is the endpoint used, https://developer.easee.cloud/reference/get_api-accounts-products
It should look something like this. There should be one or more circuits and below that one or more chargers.
Can you login to the API portal and trigger the endpoint and show the JSON returned?
[
  {
    "id": 0,
    "siteKey": "string",
    "circuits": [
          {
            "id": 0,
            "siteId": 0,
            "circuitPanelId": 0,
            "panelName": "string",
            "ratedCurrent": 0,
            "chargers": [
              {
                "id": "string",
                "name": "string",

**Comment by ricott** [comment]
There is a new test version [here](https://homey.app/a/no.easee/test/).

**Comment by Retteph** [comment]
👌🏻👍🏻
now it works
