### ISSUE TITLE
Unable to add my chargers

### ISSUE THREAD

**Issue by trondermedbart** [ricott/homey-no.easee#43]
I have two chargers - one home and one at the cabin. Getting error for both chargers. 
See attached screenshots 
![384A01D8-B9CA-45C7-9B8F-D9EE06C0AC0D](https://user-images.githubusercontent.com/31805930/213006178-d0d73935-0c4d-428c-9a02-f386030390b6.png)
![5E1A76F1-5D65-4E66-BEA7-5E3B213F057A](https://user-images.githubusercontent.com/31805930/213006190-4a528f78-5885-49aa-885b-1b50faa0c0ce.png)

![7F41557D-EDFB-4649-9ECE-EE12633A1F34](https://user-images.githubusercontent.com/31805930/213005732-b876e3cb-10e1-4f57-a997-cfdbe72acb5d.png)
![12493237-2053-4D74-95B5-3308550E3398](https://user-images.githubusercontent.com/31805930/213005752-31490974-ac23-42ca-867d-01e15ddc8d24.png)
![FD552510-6A46-4500-B911-151AD20FB688](https://user-images.githubusercontent.com/31805930/213006298-e9e01418-838b-4103-8baa-4c248b4d1e15.png)

**Comment by trondermedbart** [comment]
I did try again today and the "Easee Home 4278" charger now shows up in Homey (may have been a temp glitch?).

Still having issues with the other charger though. Have tried to remove + add the device again + restarted the app. No difference, it still claims "failed to retrieve the site if and circuit id" and shows up as "charger.name" in Homey (with red exclamation mark)

Some observations:
- Homey: Under device (charger.name) -> Advanced Settings, both the Site id and Circuit id and other settings shows up correctly.
- Homey: Under invocation statistics (in Easee Home app -> Configure), both chargers appear under "invocations by endpoint(...)".
- Both chargers appear when testing at https://developer.easee.cloud/reference/get_api-accounts-products
-  and both chargers appears there to, which makes me think there is a bug in the Easee Home app.

**Comment by ricott** [comment]
Just pushed a new release, which should solve the problem.
