### ISSUE TITLE
Can't start or stop a charge

### ISSUE THREAD

**Issue by pstokholm** [ricott/homey-no.easee#44]
When using the "Turn on" or "Turn off" it returns with an error?

![image](https://user-images.githubusercontent.com/80712531/213906269-51d59abb-695d-4bec-aafc-d6b8356ed9aa.jpeg)

**Comment by ricott** [comment]
Is this a one-time problem or do you still get this error? Network request indicates a network-related problem.

**Comment by pstokholm** [comment]
Yes, it’s still a problem 😕


Med venlig hilsen
Patrick Stokholm

Den 22. jan. 2023 kl. 14.21 skrev Richard Barkestam ***@***.***>:

﻿

Is this a one-time problem or do you still get this error? Network request indicates a network-related problem.

**Comment by robinstalesen** [comment]
Same problem for me..

**Comment by ricott** [comment]
There is a longer discussion in the [forum thread](https://community.homey.app/t/app-pro-easee-charger/31647/192), Easee have broken their API somehow. The commands endpoint which is supposed to return the outcome of the start/stop/resume/pause commands returns a 404 error

**Comment by ricott** [comment]
Easee have fixed the commands API endpoint, should work for everyone now

**Comment by pstokholm** [comment]
You are the best! Thank you!

Med venlig hilsen,

Patrick Stokholm



Den 24. jan. 2023 kl. 19.30 skrev Richard Barkestam ***@***.***>:



Easee have fixed the commands API endpoint, should work for everyone now
