### ISSUE TITLE
Flowcard failed to set Dynamic charger current API 504 Error

### ISSUE THREAD

**Issue by kmengvik** [ricott/homey-no.easee#48]
Oh! what happened here?

![image](https://user-images.githubusercontent.com/16176305/222953721-d98897b1-1b61-4bcd-adfa-fcf679f411d3.png)

**Comment by ricott** [comment]
The Easee API gives various errors from time to time. Probably an idea to build a flow that retries, and makes sure the action was performed. HTTP response code 504 means gateway timeout.
