### ISSUE TITLE
Update to new signalR streaming address

### ISSUE THREAD

**Issue by hansarh** [ricott/homey-no.easee#49]
The signalR streaming URL needs to be updated [here](https://github.com/ricott/homey-no.easee/blob/c01e6e735966ce8b2a28b1cbe32de95867aa3dfd/lib/const.js#L7)

Could you please update it to `https://streams.easee.com/hubs/chargers`

info about change here: https://developer.easee.cloud/changelog/signalr-uri-change

**Comment by hansarh** [comment]
@ricott Hope you are able to look into this in the nearest future

**Comment by ricott** [comment]
Sorry for the slow response, the app doesn't use SignalR today.
I'll remove the constant 👍
