### ISSUE TITLE
Increase dynamic circuit current dosnt work

### ISSUE THREAD

**Issue by Totnet91** [ricott/homey-no.easee#5]
Hi dear,
The Increase dynamic circuit current dosent work for me. Do you know why ? I would like to increase the current when the totally load is high in the house.
Br
Tornet91

**Comment by ricott** [comment]
Hi!
There are quite a few changes in the test version of the app. Can you try that version, guessing you are not using it now?

**Comment by Totnet91** [comment]
Im using v1.1.4

**Comment by shaarkys** [comment]
@Totnet91 , install 1.2.2 - https://homey.app/en-us/app/no.easee/Easee-Home/test/

**Comment by ricott** [comment]
Please open a new ticket if still relevant
