### ISSUE TITLE
Not able to activate

### ISSUE THREAD

**Issue by JonadJaconelli** [ricott/homey-no.easee#50]
Hi , i am running the latest version of your easee app and am not able to activate my charger.
I am using homey pro 2023.

Is this a known bug?
Regards. Jonas

**Comment by ricott** [comment]
Hi!

No known bug, exactly what action are you using and what is the error message you get?

**Comment by ricott** [comment]
under settings on the device there are two fields, `last API error` and `logs`.
you can also send a manual diagnostic report from within the Homey mobile app. This is below settings on the app level, not device.
