### ISSUE TITLE
Adding easee charger to homey

### ISSUE THREAD

**Issue by T0masen** [ricott/homey-no.easee#51]
Hey. Trying to add my easee charger to homey and is getting"could not find pair session"
![Screenshot_20230526_171508_Homey](https://github.com/ricott/homey-no.easee/assets/43578102/46ca0db0-e88a-4086-99b3-84478ee5bf5a)

**Comment by ricott** [comment]
I'm guessing this problem is solved by now, otherwise re-open the ticket.
