### ISSUE TITLE
New api url from October 3rd 2023

### ISSUE THREAD

**Issue by hansarh** [ricott/homey-no.easee#54]
The [api URL is changing](https://developer.easee.cloud/docs/integrations-30) to only be supported on api.easee.com from October 3rd 2023

Are you updating api.easee.com to be the only used api URL by then?

**Comment by ricott** [comment]
Thanks for letting me know 👍
Change is released in a test version, will push to live in a day or two.

**Comment by Roaldoien** [comment]
Is this the problem as i cant get this working on a homey pro 2023?

**Comment by ricott** [comment]
@Roaldoien Not related at all, as you can see it will stop working on the 3rd of October.
If you have a problem you can open a new ticket and explain what you are trying to do and what error message you get.

**Comment by hansarh** [comment]
Great:) hope to see v1.7.1 be released as the stable version soon!

**Comment by ricott** [comment]
v1.7.1 is live 👍
