### ISSUE TITLE
On / Off

### ISSUE THREAD

**Issue by chamtl** [ricott/homey-no.easee#56]
Hi,
I’m not able to turn it on and off from the homey iOS app.

**Comment by ricott** [comment]
If you add the turn on / off to a flow and trigger it manually you will see the error you get.
There are multiple reasons why it may not work. Easee's cloud services are known to have problems from time to time. You charger may have poor internet connectivity. Remember that the communication path here is Homey app -> Easee cloud -> Charger, the Homey app doesn't talk directly to your charger.

**Comment by chamtl** [comment]
Hi,
I have an integration from home assistant and that is working fine. So my guess is that it is a Homey issue. I don’t get any error.

**Comment by ricott** [comment]
You can check the device settings for last api error, do you see something there? You can also trigger a manual diagnostic report.

The Homey app sends a start charging command to easee cloud, ease cloud will send the command to the charger and expose a cloud endpoint that exposes the result of the command it sent to the charger. The Homey app use this endpoint and verifies if the command was actually accepted by the charger or not. It the start command wasn't accepted the Homey app issues a resume command. Again to easee cloud, which in turn relays this to the charger. Exposes an endpoint with the outcome of the resume command and this endpoint is again polled (max 50 times) for the outcome.
If in the end neither start nor resume was accepted by the charger the error is returned to the client.
This is way more advanced, and in my mind better, than what the HM app is doing. 

There are ~6k chargers being controlled by the homey app, so if there was a problem with the Homey app I guess we would see more issues here than yours. I myself also use the Homey app to control my chargers, and it charged this night as expected.

**Comment by chamtl** [comment]
Thanks for the reply.

This is from the API:

2023-09-29T11:40:52.158Z
Error: Invalid Capability: target_charger_current
    at ChargerDevice.getCapabilityOptions (/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:592:25)
    at ChargerDevice.fetchCapabilityOptions (/app/drivers/charger/device.js:204:32)
    at /app/drivers/charger/device.js:548:42
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


This is from the log:

	2023-09-29T08:05:52.318Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T08:10:51.497Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T08:15:51.461Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T08:20:51.458Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T08:25:51.502Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T08:30:51.457Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T08:35:51.500Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T08:40:51.490Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T08:45:51.508Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T08:50:51.501Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T08:50:52.611Z We have a new access token from TokenManager
,2023-09-29T08:55:51.554Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T09:00:51.515Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T09:05:51.663Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T09:10:51.670Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T09:15:51.654Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T09:20:51.662Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T09:25:51.754Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T09:30:51.754Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T09:35:51.820Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T09:40:51.819Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T09:45:51.816Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T09:46:53.585Z We have a new access token from TokenManager
,2023-09-29T09:50:51.817Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T09:55:51.842Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T10:00:51.832Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T10:05:51.863Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T10:10:51.852Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T10:15:51.855Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T10:20:51.891Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T10:25:51.947Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T10:30:51.940Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T10:35:51.977Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T10:40:51.979Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T10:40:54.741Z We have a new access token from TokenManager
,2023-09-29T10:45:52.039Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T10:50:52.020Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T10:55:52.050Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T11:00:52.045Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T11:05:52.084Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T11:10:52.087Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T11:15:52.100Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T11:20:52.109Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T11:25:52.178Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T11:30:52.149Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T11:35:52.163Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T11:36:55.479Z We have a new access token from TokenManager
,2023-09-29T11:40:52.159Z Failed to read capability options max of 'target_charger_current'. Athom bugs ...
,2023-09-29T11:41:31.261Z Starting charge
,2023-09-29T11:41:33.080Z Failed to start charging, lets try resume

**Comment by chamtl** [comment]
I get this error in the app:
![IMG_0015](https://github.com/ricott/homey-no.easee/assets/54553542/0dd02e49-3229-447f-8a7c-80cc3745d27e)

**Comment by chamtl** [comment]
I get this error in the app:
![IMG_0015](https://github.com/ricott/homey-no.easee/assets/54553542/8347e31f-edb7-4ce7-a116-4158c5bcbefb)

**Comment by chamtl** [comment]
I got it to work. It is controlled another way then ha 😬
