### ISSUE TITLE
Wrong effect

### ISSUE THREAD

**Issue by Sethakan** [ricott/homey-no.easee#59]
Both my easee charger and equaliser has stuck around 8000w in insights. I have restarted the charger and app in homey, no change.
![Screenshot_20231026-190551](https://github.com/ricott/homey-no.easee/assets/112776845/3e43b88c-063e-4e57-8cae-d2bbec3524cf)

**Comment by ricott** [comment]
Haven't seen this before

Tried restarting the Homey mobile app?
If you check in the [Homey web app](https://my.homey.app/), do you see the same behaviour there?
What does the Easee mobile app/web state?

**Comment by Sethakan** [comment]
Yes I've restarted the app and it says the same number in effect in homey
web app. Im 99% sure that deleting the app and reinstall will fix it, but i
don't like that fix.

Anyway, that's what I'm gonna do, tomorrow🤘

Håkan

Den tors 26 okt. 2023 22:04Richard Barkestam ***@***.***>
skrev:

**Comment by ricott** [comment]
If the web app and the mobile app shows the same inaccurate numbers, then I would guess the Homey Easee App have died.
When you said you have restarted the app, which app? The Homey mobile and/or the Homey Easee app?
There is always an option to also share a manual diagnostic report, then some parts of the logs are sent via email to me. Don't restart the Homey Easee app before doing so though, since then logs of problem are gone.

**Comment by Sethakan** [comment]
I have restarted both apps and the charger at the fuses.

Ok i think i got it now. My friend where hacked a few weeks ago, then i
changed alot of Week passwords.
In homey apps is not possible to do that, change passwords and you du not
get a warning.

So, my bad.

Thanks for tryin to help.

f2bcbe8d-5cf3-4168-a075-1132127b035c

Den tors 26 okt. 2023 22:29Richard Barkestam ***@***.***>
skrev:

**Comment by ricott** [comment]
and yes, you are correct 😀
From the diag report.

Will think about possibility to show this somehow.

```
Error: Login failed! Call '/api/accounts/login' failed, HTTP status code '400', and message '{
  errorCode: 100,
  errorCodeName: 'InvalidUserPassword',
  type: null,
  title: 'Username or password is invalid',
  status: 400,
  detail: '[Empty in production]',
  instance: null,
  extensions: {}
}'
```
