### ISSUE TITLE
Feature: pause/resume flowcards

### ISSUE THREAD

**Issue by erimatnor** [ricott/homey-no.easee#62]
The pause/resume functionality exists in the code, but there are no flow cards to control it. Having the ability to pause and resume a charging session via a flow would be great as it doesn't require the user to re-authenticating with the charger.

**Comment by ricott** [comment]
The turn on and off actions tries both "start and resume" and "stop and pause" as needed
https://github.com/ricott/homey-no.easee/blob/0b90468db6f480acacfb626de9f549c60d2abf30/drivers/charger/device.js#L683

If I recall correctly, what pause and resume does is to set dynamic charger current to 0 to stop charging and back to previous value to start charging again. If you don't want to use turn on/off this is a possibility.
