### ISSUE TITLE
Current and wattage not nukled when stopped charging

### ISSUE THREAD

**Issue by arnebenjamin** [ricott/homey-no.easee#65]
I have noticed multiple times that the Easee unit in Homey keeps a value on wattage and ampere when the session is canceled mid charge. 
the values should be nulled when the state is changed from «Charging» to «off»/«Standby»?

![image](https://github.com/ricott/homey-no.easee/assets/30862757/19a429ca-a2ea-46b0-ae96-1400a20fff62)

**Comment by ricott** [comment]
Those values today are read from the Easee cloud, together with all the other values. 
Here it looks like the app stopped refreshing all values?

**Comment by ricott** [comment]
Re-open if the problem still persists
