### ISSUE TITLE
No value updates for 2 days.

### ISSUE THREAD

**Issue by Eskjon** [ricott/homey-no.easee#66]
No values have been updated for two days.

Cannot re-establish connection via "maintenance" action.

Latest API error:
2024-01-05T20:07:52.964Z
Error: Login failed! Call '/api/accounts/login' failed, HTTP status code '400', and message '{
  errorCode: 100,
  errorCodeName: 'InvalidUserPassword',
  type: null,
  title: 'Username or password is invalid',
  status: 400,
  detail: '[Empty in production]',
  instance: null,
  extensions: {}
}'
    at /lib/loginHelper.js:98:39
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /drivers/charger/device.js:151:13
    at async ChargerDevice._onSetCapabilityValue (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:1:2134)

Don't know where to re-enter credentials.

**Comment by ricott** [comment]
Try and restart the app, but if message is `InvalidUserPassword` then I suspect that is the problem.

**Comment by Eskjon** [comment]
Hi,

I have tried restarting the app, as well as disabling and enabling it. I think I've done everything but deleting the units and re-adding them. I would like to avoid that because it means updating al the flows and so on...
I updated the password recently. I suspect that is the cause of the issue. However, I fail to find where I update it in the Homey app.

//Jon



________________________________

**Comment by Eskjon** [comment]
Hi,

I have tried restarting the app, as well as disabling and enabling it. I think I've done everything but deleting the units and re-adding them. I would like to avoid that because it means updating al the flows and so on...
I updated the password recently. I suspect that is the cause of the issue. However, I fail to find where I update it in the Homey app.

//Jon


________________________________

**Comment by Eskjon** [comment]
Hi again,

I have an Easee load balancer which is not implemented in any flows and was having the same issues. I tried removing and re-adding it and it resolved the issue because I was forced to update the credentials.

It will probably work for the wallbox as well but I'd like to avoid it...
If the app doesn't support updating the credentials, maybe that is a feature worth adding.

//Jon


________________________________
Från: Jon Eskils ***@***.***>
Skickat: lördag, januari 6, 2024 1:00:47 em
Till: ricott/homey-no.easee ***@***.***>; ricott/homey-no.easee ***@***.***>
Kopia: Author ***@***.***>
Ämne: Re: [ricott/homey-no.easee] No value updates for 2 days. (Issue #66)

Hi,

I have tried restarting the app, as well as disabling and enabling it. I think I've done everything but deleting the units and re-adding them. I would like to avoid that because it means updating al the flows and so on...
I updated the password recently. I suspect that is the cause of the issue. However, I fail to find where I update it in the Homey app.

//Jon



________________________________

**Comment by ricott** [comment]
Yes, if you change the password today you need to re-add the device I'm afraid.
Will look into option of updating the password 👍

**Comment by ricott** [comment]
Repair is available in the latest test version
https://homey.app/a/no.easee/test/
