### ISSUE TITLE
Cant start charging timeout

### ISSUE THREAD

**Issue by Abbiz00** [ricott/homey-no.easee#69]
The app not working with the new homey pro.
Works fine with the old one. 

58c7f85a-59b0-4cab-b99d-8f73464d9235

**Comment by ricott** [comment]
The app works fine on the new Homey Pro, I have one myself with two Easee chargers.
There are however sometimes communication problems between Easee cloud and the charger. As you probably know the Homey app doesn't communicate directly with the charger, it talks to Easee cloud which in turn talks to the charger.

What I can see in your diag reports is that you seem to check the charger status very frequently. Every 5 seconds you check twice (different flows?) if the charger is charging. Don't know what you want to achieve with this logic, but I would probably use the trigger instead and filter for the Charging status.

Then I see a few entires of errors which I saw for the first time the other day. This is the same problem as this [ticket](https://github.com/ricott/homey-no.easee/issues/68#issuecomment-1921195966).
`Error: Command didn't return a state after '50' attempts!`

Could it be that you are sending commands to the charger frequently to fill up the queue on the Easee cloud side?

**Comment by Abbiz00** [comment]
Thank you for your reply. I will test change my settings./AlbinSkickat från min Galaxy
-------- Originalmeddelande --------Från: Richard Barkestam ***@***.***> Datum: 2024-02-06  09:19  (GMT+01:00) Till: "ricott/homey-no.easee" ***@***.***> Kopia: Abbiz00 ***@***.***>, Author ***@***.***> Ämne: Re: [ricott/homey-no.easee] Cant start charging timeout (Issue #69) 
The app works fine on the new Homey Pro, I have one myself with two Easee chargers.
There are however sometimes communication problems between Easee cloud and the charger. As you probably know the Homey app doesn't communicate directly with the charger, it talks to Easee cloud which in turn talks to the charger.
What I can see in your diag reports is that you seem to check the charger status very frequently. Every 5 seconds you check twice (different flows?) if the charger is charging. Don't know what you want to achieve with this logic, but I would probably use the trigger instead and filter for the Charging status.
Then I see a few entires of errors which I saw for the first time the other day. This is the same problem as this ticket.
Error: Command didn't return a state after '50' attempts!
Could it be that you are sending commands to the charger frequently to fill up the queue on the Easee cloud side?
