### ISSUE TITLE
IT net no information about voltage

### ISSUE THREAD

**Issue by knutmw** [ricott/homey-no.easee#7]
Hi

I love this app, but when i use the easee equalizer in homey i do not get voltages on norwegian IT net. In the easee app i get this.

In homey when i look inside the settings, i can see that the power grid type is set to TN_2_Phase_2_3_4. When i click it i can't choose anything else.

Is it a way to change the grid type in the homey app so i can get the voltages. 

Current and power works like it should
![Screenshot_20210923-112911_Homey](https://user-images.githubusercontent.com/58953069/134485178-245738ff-3663-42b6-92e0-16eea06af861.jpg)
.

**Comment by ricott** [comment]
Is this still the case in the current version of the app?

**Comment by knutmw** [comment]
Yes, it's still no voltage tested it on IOS and Android.
But as you see on the picture the grid type is TN_2_PHASE. and i have a IT grid?
![Screenshot_20220202-123327_Homey](https://user-images.githubusercontent.com/58953069/152146507-c35dc755-0758-4b7c-98f7-eb6425ebd6b6.jpg)
.

**Comment by ricott** [comment]
There is an enum here for the grid type that Easee is sending, nothing the Homey app tries to figure out in any other way.
https://github.com/ricott/homey-no.easee/blob/a088412361c769a9e34dcc5ee9bfc7d75a2fdb63/lib/enums.js#L46

I asked Easee a question around the mapping of voltage depending on grid type - let's see if there is a reply.

**Comment by ricott** [comment]
Testversion out, please give it a swing
https://homey.app/a/no.easee/test/

**Comment by ricott** [comment]
Should be solved in latest version
