### ISSUE TITLE
Missing status "NO car connected"

### ISSUE THREAD

**Issue by Homey4Osty** [ricott/homey-no.easee#73]
Hello,
I've lots of status available at my homey app and the flows.
![image](https://github.com/ricott/homey-no.easee/assets/146454771/aff7e5cb-f3af-4292-b8d5-d108ea73a65b)

But I'm missing the status "NO car connected". This status is shown in my easee-app and also at the easee-cloud.
Cloud-Screenshot:
![image](https://github.com/ricott/homey-no.easee/assets/146454771/4e26ef04-8c08-45e5-a8db-bf255fe399d7)

Is it possible to add this status?

Thanks.

Have a nice day!
Osty

**Comment by Homey4Osty** [comment]
@ricott : is there a chance to get the status "no car connected"? Thx

**Comment by Homey4Osty** [comment]
Status "Standby" = "No car connected"

**Comment by roel53** [comment]
Status "Standby" is not equal to "No Car connected". The status "Standby" is also 'sent' when the charger stops charging...
So no real solution...
