### ISSUE TITLE
Compatibility with different Easee Wallbox types

### ISSUE THREAD

**Issue by gfacchinetti74** [ricott/homey-no.easee#75]
Hi

I like the Easee Wallbox, it looks good,has smart functions and should be able to be integrated into my Homey Pro setup.

On the Homey App page it is written that it will support the Easee Charger and Easee Equalizer but there are many Easee Wallbox types on the market. I life in Switzerland and not all types are available here.

The types not seen in Switzerland:
- The one
- The Charger (as it is written on the Homey app page)

The types available in Switzerland:
- Chargelite
- Home

I am looking into buying a “Home” but I don’t fin any information if the Home is supported and if the flow cards flow cards work with the home.

Did anybody test this successfully?

Regards,
Gianni

**Comment by ricott** [comment]
Since the app communicates with the Easee cloud services and not the actual charger - then any charger should work is my assumption - since Easee only has one set of web APIs.
