### ISSUE TITLE
Support for new Energy widget dashboard?

### ISSUE THREAD

**Issue by bjornbb** [ricott/homey-no.easee#80]
The new energy widget/dashboard can show EV chargers:
https://homey.app/en-us/news/introducing-the-homey-energy-dongle

Easee does not show up. It is my understanding that the device must be classified as 'wallbox' to show up. Can you look into that?

**Comment by ricott** [comment]
Yes, I see there is a new device type as of firmware v12 - `evcharger`
Will add it and then also need to update the minimum version required to install the app

**Comment by ricott** [comment]
There is a new [test version](https://homey.app/a/no.easee/test/)

**Comment by bjornbb** [comment]
Do I need to remove and add the device again?

Should I see a different class here on the dev device page?
![image](https://github.com/user-attachments/assets/36a0e3bb-114a-4a08-8a01-461991d2d7c9)

**Comment by ricott** [comment]
That is an excellent comment of course, I think we should be able to change class for existing devices - let me check again.

**Comment by ricott** [comment]
New test version out

**Comment by bjornbb** [comment]
Great :)

Class | evcharger

![IMG_0592](https://github.com/user-attachments/assets/01f05022-a340-4c2e-b4ce-b1ced6c9cfa3)
